routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/testhome', 'HomeController@test')->name('testhome');
// Route::get('/home/news', 'CategoriesController@index')->name('News');
// We use resource controller so we commented  
//Route::get('/home/categories', 'CategoriesController@index')->name('listCategories');
// Route::get('/home/categories/detail/{id}', 'CategoriesController@detail')->name('DetailCategory');

Route::resource('/admin/categories','Admin\CategoriesController',['as'=>'admin']);
Route::resource('/admin/news','News\NewsController',['as'=>'admin']);

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    //
}

app/Http/Controllers/News/NewsController.php
<?php

namespace App\Http\Controllers\News;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\News;
class NewsController extends Controller
{
    public function __construct(){
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $arr['news'] = News::all();
        return view('admin.news.news')->with($arr);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   

        return view('admin.news.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, News $news)
    {   
        $validatedData = $request->validate([
            'title' => ['required','min:2'],
            'description' => ['required','min:10'],
            'author' => ['required','min:3'],
        ]);
        $news->title = $request->title;
        $news->description = $request->description;
        $news->author = $request->author;
        $news->save();
        return redirect('admin/news');   

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(News $news)
    {   
        $arr['news'] = $news;
        return view('admin.news.edit')->with($arr);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, News $news)
    {
        $validatedData = $request->validate([
            'title' => ['required','min:2'],
            'description' => ['required','min:10'],
            'author' => ['required','min:3'],
        ]);
        $news->title = $request->title;
        $news->description = $request->description;
        $news->author = $request->author;
        $news->save();
        return redirect('admin/news');        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        news::destroy($id);
        return redirect('admin/news');
    }
}

resources/views/admin/news/create.blade.php
@extends('layouts.adminlayout');
@section('containt')
<div class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0 text-dark">Add News</h1>
			</div><!-- /.col -->
			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
					<li class="breadcrumb-item"><a href="{{ route('home') }}">Dashboard</a></li>
					<li class="breadcrumb-item active">Add News</li>
				</ol>
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.container-fluid -->
</div>

<section class="content">
	<div class="row">
		<div class="col-12">
			<div class="card">
				<div class="card-header">
					<h3 class="card-title">Add News </h3>
				</div>
				<!-- /.card-header -->
				<div class="card-body">
					<form action="{{ route('admin.news.store') }}" method="post">
						
						@csrf
						
						<div class="form-group">
							<div class="row">
								<label  class="col-md-3">Title</label>
								<div class="col-md-6">
									<input type="text" class="form-control" name="title"  value="{{ old('title') }}" placeholder="Enter Title">	
									@error('title')
									<div class="alert alert-danger">{{ $message }}</div>
									@enderror
								</div>
							</div>
						</div>

						<div class="form-group">
							<div class="row">
								<label  class="col-md-3">Description</label>
								<div class="col-md-6">
									<textarea class="form-control" name="description" rows="5">
										{{ old('description') }}
									</textarea>

									@error('description')
									<div class="alert alert-danger">{{ $message }}</div>
									@enderror
								</div>
							</div>
						</div>

						<div class="form-group">
							<div class="row">
								<label  class="col-md-3">Author</label>
								<div class="col-md-6">
									<input type="text" class="form-control" name="author"  value="{{ old('author') }}" placeholder="Enter Author">	
									@error('author')
									<div class="alert alert-danger">{{ $message }}</div>
									@enderror
								</div>
							</div>
						</div>

						<div class="form-group">
							<input type="submit"  name='submit'class="btn btn-primary">
						</div>

					</form>
				</div>
			</div>
		</div>
	</div>
</section>
@endsection

resources/views/admin/news/edit.blade.php
@extends('layouts.adminlayout');
@section('containt')
<div class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0 text-dark">Edit News</h1>
			</div><!-- /.col -->
			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
					<li class="breadcrumb-item"><a href="{{ route('home') }}">Dashboard</a></li>
					<li class="breadcrumb-item active">Edit News</li>
				</ol>
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.container-fluid -->
</div>

<section class="content">
	<div class="row">
		<div class="col-12">
			<div class="card">
				<div class="card-header">
					<h3 class="card-title">Edit News </h3>
				</div>
				<!-- /.card-header -->
				<div class="card-body">

					<form action="{{ route('admin.news.update',$news->id) }}" method="POST">
						@method('PUT')
						@csrf

							<div class="form-group">
							<div class="row">
								<label  class="col-md-3">Title</label>
								<div class="col-md-6">
									<input type="text" class="form-control" name="title"  value="{{ $news->title }}" placeholder="Enter Title">	
									@error('title')
									<div class="alert alert-danger">{{ $message }}</div>
									@enderror
								</div>
							</div>
						</div>

						<div class="form-group">
							<div class="row">
								<label  class="col-md-3">Description</label>
								<div class="col-md-6">
									<textarea class="form-control" name="description">{{ $news->description }}
									</textarea>
									@error('description')
									<div class="alert alert-danger">{{ $message }}</div>
									@enderror
								</div>
							</div>
						</div>

						<div class="form-group">
							<div class="row">
								<label  class="col-md-3">Author</label>
								<div class="col-md-6">
									<input type="text" class="form-control" name="author"  value="{{ $news->author }}" placeholder="Enter Author">	
									@error('author')
									<div class="alert alert-danger">{{ $message }}</div>
									@enderror
								</div>
							</div>
						</div>

						<div class="form-group">
							<input type="submit"  name='submit'class="btn btn-primary">
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>
@endsection

resources/views/admin/news/news.blade.php
@extends('layouts.adminlayout');
@section('containt')
<div class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0 text-dark">News</h1>
			</div><!-- /.col -->
			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
					<li class="breadcrumb-item"><a href="{{ route('home') }}">Dashboard</a></li>
					<li class="breadcrumb-item active">News</li>
				</ol>
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.container-fluid -->
</div>
<div>
	<a href=" {{ route('admin.news.create') }}">
	<button class="btn btn-primary m-2">Add New News</button>
	</a>
</div>
<section class="content">
	<div class="row">
		<div class="col-12">
			<div class="card">
				<div class="card-header">
					<h3 class="card-title">News List</h3>
				</div>
				<!-- /.card-header -->
				<div class="card-body">
					<table id="example2" class="table table-bordered  table-hover">
						<thead class="bg-light ">
							<tr>
								<th>No</th>
								<th>Title</th>
								<th>Description</th>
								<th>Author</th>
								<th colspan="2" class="text-center">Action</th>
							</tr>
						</thead>
						<tbody>
							@foreach($news as $c)
							<tr>
								<td>{{ $c->id }}</td>
								<td>{{ $c->title }} </td>
								<td>{{ $c->description }} </td>
								<td>{{ $c->author }} </td>
								<td><a class="btn btn-primary" href="{{ route('admin.news.edit',$c->id) }}">Edit</a> </td>
								<td>
									<form action="{{ route('admin.news.destroy',$c->id) }}" method="post">
										@csrf
										@method('DELETE')
									<input type="submit" class="btn btn-danger" name="submit" value="Delete">
									</form>
								 </td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</section>
@endsection